rimeSystem:
  clusterAutoscaler: ${install_cluster_autoscaler}
  externalDns: ${install_external_dns}
  awsLoadBalancerController: ${install_lb_controller}
  metricsServer: ${install_metrics_server}

aws-load-balancer-controller:
  image:
    repository: "${docker_registry}/robustintelligencehq/aws-alb-ingress-controller"
    tag: "v2.4.2"
  imagePullSecrets:
    - name: ${docker_secret_name}
  clusterName: "${cluster_name}"
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${lb_controller_role_arn}"
  region: "${region}"

cluster-autoscaler:
  image:
    repository: "${docker_registry}/robustintelligencehq/cluster-autoscaler"
    tag: "v1.21.0"
    pullSecrets:
      - ${docker_secret_name}
  autoDiscovery:
    clusterName: "${cluster_name}"
  awsRegion: "${region}"
  rbac:
    serviceAccount:
      annotations: {
        eks.amazonaws.com/role-arn: "${cluster_autoscaler_role_arn}"
      }

external-dns:
  image:
    repository: "${docker_registry}/robustintelligencehq/external-dns"
    tag: "v0.12.0"
  txtOwnerId: ${cluster_name}
  imagePullSecrets:
    - name: ${docker_secret_name}
  domainFilters:
%{ for domain in domains ~}
  - ${domain}
%{ endfor ~}
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${dns_role_arn}"

metrics-server:
  image:
    repository: "${docker_registry}/robustintelligencehq/metrics-server"
    tag: "v0.6.1"
  imagePullSecrets:
    - name: ${docker_secret_name}

cert-manager:
  enabled: ${enable_cert_manager}
  installCRDs: true
  global:
    imagePullSecrets:
      - name: ${docker_secret_name}
  image:
    registry: ${docker_registry}
    repository: robustintelligencehq/cert-manager-controller
  webhook:
    image:
      registry: ${docker_registry}
      repository: robustintelligencehq/cert-manager-webhook
  cainjector:
    image:
      registry: ${docker_registry}
      repository: robustintelligencehq/cert-manager-cainjector
  startupapicheck:
    image:
      registry: ${docker_registry}
      repository: robustintelligencehq/cert-manager-ctl
