# Value overrides created by the ri_firewall_helm_release Terraform module.
riFirewall:

  secrets:
    existingIntegrationSecretsName: ${integration_secrets_name}

  images:
    backendImage:
      name: "robustintelligencehq/rime-backend:${ri_firewall_version}"
      pullPolicy: "${pull_policy}"
    firewallServerImage:
      name: "robustintelligencehq/rime-testing-engine-dev:${ri_firewall_version}"
      pullPolicy: "${pull_policy}"

  firewallServer:
    serviceAccount:
      name: ${firewall_server_service_account_name}
      annotations: {
        eks.amazonaws.com/role-arn: ${blob_store_config.role_arn}
      }

  fileStorageServer:
    config:
      storageBucketName: ${blob_store_config.s3_bucket_name}
      endpoint: "s3.amazonaws.com"
      type: "s3"
    serviceAccount:
      name: ${file_storage_server_service_account_name}
      annotations: {
        eks.amazonaws.com/role-arn: ${blob_store_config.role_arn}
      }

  ingress:
    annotations: {
      # # Uncomment if using externalDns (from rime-kube-system) and fill out the hostname
      # # accordingly (e.g., "rime.${domain}")
      external-dns.alpha.kubernetes.io/hostname: "${domain}",
    }
    labels: {}
    tls: []

ingress-nginx:
  controller:
    image:
      registry: "docker.io"
      image: "robustintelligencehq/ingress-nginx-controller"
      tag: "v1.3.1"
      digest: "sha256:d3642f55a6a7a102a9a579b3382fe73869c73890de4c94f28e36ba5e07925944"
    scope:
      enabled: true
      namespace: ${namespace}
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${acm_cert_arn}"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
