rimeSystem:
  clusterAutoscaler: ${install_cluster_autoscaler}
  externalDns: ${install_external_dns}
  awsLoadBalancerController: ${install_lb_controller}
  metricsServer: ${install_metrics_server}

cluster-autoscaler:
  autoDiscovery:
    clusterName: "${cluster_name}"
  awsRegion: "${region}"
  rbac:
    serviceAccount:
      annotations: {
        eks.amazonaws.com/role-arn: "${cluster_autoscaler_role_arn}"
      }
  podAnnotations: {
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  }
  cloudProvider: aws

external-dns:
  provider: "aws"
  domainFilters:
%{ for domain in domains ~}
  - ${domain}
%{ endfor ~}
  policy: sync
  registry: txt
  txtOwnerId: "rime"
  rbac:
    create: true
  serviceAccount:
    name: external-dns
    annotations:
      eks.amazonaws.com/role-arn: ${dns_role_arn}
  logFormat: json

aws-load-balancer-controller:
  clusterName: "${cluster_name}"
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${lb_controller_role_arn}"
  region: "${region}"

metrics-server:
  apiService:
    create: true
