rimeSystem:
  clusterAutoscaler: ${install_cluster_autoscaler}
  externalDns: ${install_external_dns}
  awsLoadBalancerController: ${install_lb_controller}
  metricsServer: ${install_metrics_server}

cluster-autoscaler:
  autoDiscovery:
    clusterName: "${cluster_name}"
  awsRegion: "${region}"
  rbac:
    serviceAccount:
      annotations: {
        eks.amazonaws.com/role-arn: "${cluster_autoscaler_role_arn}"
      }

external-dns:
  domainFilters:
%{ for domain in domains ~}
  - ${domain}
%{ endfor ~}
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${dns_role_arn}

aws-load-balancer-controller:
  clusterName: "${cluster_name}"
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "${lb_controller_role_arn}"
  region: "${region}"
